server {
    listen 80;
    server_name ollama.site-al.ru;
    client_max_body_size 100m;

    location /.well-known/acme-challenge/ {
        root /var/www/ollama.site-al.ru;
    }

    location / {
        return 404;
    }
}
